<x-layout>
  <x-slot:title>{{ $title }}</x-slot>
  
  <h1 style="text-align: center;">Kim Ji-won</h1>
  <p style="text-align: justify">Kim Ji-won (Hangul: 김지원; lahir pada 19 Oktober 1992) adalah aktris berkebangsaan Korea Selatan. Ia bermain sebagai pemeran utama dalam film Romantic Heaven (2011) dan muncul dalam seri drama To the Beautiful You (2012), The Heirs (2013), Descendants of the Sun (2016), dan menjadi pemeran utama drama populer Fight for My Way (2017), Arthdal Chronicles (2019), Lovestruck in The City (2020/2021), My Liberation Diary (2022), dan Queen of Tears (2024).</p>
  <p>Ji-won pertama kali terjun ke industri hiburan pada tahun 2008 dengan berperan kecil dalam drama dan muncul di beberapa iklan (Oran-C dan Lollipop bersama Big Bang) dan video musik ("Gossip Boy" milik Younha). Selain itu, Ia juga membintangi film Romantic Heaven, namun Ji-won baru mulai mendapatkan perhatian publik setelah memainkan peran utama dalam drama What's Up yang tayang pada tahun 2011. Perannya yang paling dikenal adalah dalam serial drama High Kick: Revenge of the Short Legged pada tahun 2011 sebagai Kim Ji-won. Pada tahun 2012, ia berperan dalam To the Beautiful You sebagai Seol Han-na. Ia juga membintangi film Horror Stories 2 dan muncul dalam video musik untuk lagu "Til the Sun Rises" milik Baek Seung-heon, bersama Jaejoong dari JYJ. Pada tahun 2013, Ji-won berperan sebagai Yoo Ra-hael, seorang ahli waris chaebol dalam drama The Heirs. <br><br></p>
  
  <h1 style="text-align: center">Metro Exodus</h1>
  <p style="text-align: justify">Metro Exodus adalah permainan penembak orang pertama game dengan elemen horor sintasan dan siluman. Terletak di gurun pasca-apokaliptik bekas Federasi Rusia, pemain harus mengatasi bahaya baru dan terlibat dalam pertempuran melawan makhluk mutasi serta orang yang jahat. Pemain memiliki segudang persenjataan yang dapat dikustomisasi dengan memulung bahan dan menggunakan sistem kerajinan. Permainan ini menampilkan perpaduan level linier dan lingkungan dunia terbuka . Ada juga sistem cuaca yang dinamis, siklus siang-malam, dan lingkungan yang berubah seiring dengan musim ketika cerita berlanjut. Metro Exodus dikembangkan oleh 4A Games. Pengembangan permainan ini dimulai sejak tahun 2014 di studio 4A Games di Malta dan Kiev. Permainan ini memakai 4A Engine.</p>
</x-layout>